### ISSUE TITLE
Prevent duplicate names

### ISSUE THREAD

**Issue by Avygeil** [Avygeil/base_enhanced#4]

**Comment by Avygeil** [comment]
Instead of preventing duplicate names let's allow them but append a clientNum just in chat/console if 2 names are the same. Requires a better CleanName that will strip unseen color codes so we can't have ambiguous names.

**Comment by deathsythe47** [comment]
Why not scoreboard, too? It would be confusing because you wouldn't be able to remember who is who.

`onasi (5) was killed by onasi (4)` Who died? I can't check scoreboard to confirm.
`onasi (3): join my team please` What team am I supposed to join? I can't tell which team onasi (3) is on.

If you can't see who is onasi (3,4,5) on the scoreboard, then there's not much use in doing it elsewhere imo.

**Comment by Avygeil** [comment]
That's why admins can rename people, players rarely do that anyway. It's more to make the difference between fags named spec or Padawan, or just fakers who want to talk for other people in chat thinking it's fun to say ^5GET!!!!!!! named as someone else. I can't recall a pug where two guys had the exact same name in a while, and if they do again they can just be renamed anyway. Also people in CTF like to usebug and will likely take the name of offline people so they can't use their own name later lol

Also for your 1st example, seeing exactly who died isn't as much of an issue in ctf as it is in siege. Preventing duplicate names sounds more useful in siege for that exact reason. Your 2nd example reminded me I have to color lines by team on /clientlist which fixes that anyway.

**Comment by entdark** [comment]
How about to add S_COLOR_WHITE"(SPEC)" just in chat for the spec abusers?

**Comment by Avygeil** [comment]
b9e6118354c8e53fd24cde19c0a0300140d5723d
